services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d yopta" ]
      interval: 30s
      timeout: 10s
      retries: 5
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  redis:
    image: redis:alpine3.16
    container_name: redis-wsbe
    env_file: .env
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "6379:6379"
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    hostname: kafka
    networks: [ app_network ]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # кворум контроллеров. Один узел — один голос
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      # обычные параметры
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      CLUSTER_ID: 'q1Sh-9_ISia_zwGINzRvyQ'
    # админка для того, чтобы можно было посмотреть на UI Kafka
    # Будет открываться по адресу http://localhost:8080/ui/clusters/local/broker
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on: [ kafka ]
    networks: [ app_network ]
    ports: [ "8080:8080" ]
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - "27018:27017"
    restart: unless-stopped
networks:
  app_network: {}
  db:
    driver: bridge

volumes:
  minio_storage:
  db:
  mongo:
